export const mockCategories = [
  {
    id: '1',
    name_ar: 'الملابس الرجالية',
    name_en: 'Men\'s Clothing',
    description_ar: 'أحدث صيحات الموضة الرجالية من قمصان وبنطلونات وملابس رياضية',
    description_en: 'Latest men\'s fashion trends including shirts, pants, and sportswear',
    image_url: 'https://images.unsplash.com/photo-1490367532201-b9bc1dc483f6?w=800&h=600&fit=crop',
    slug: 'mens-clothing',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name_ar: 'الملابس النسائية',
    name_en: 'Women\'s Clothing',
    description_ar: 'مجموعة متنوعة من الفساتين والبلوزات والملابس العصرية للنساء',
    description_en: 'Diverse collection of dresses, blouses, and modern women\'s wear',
    image_url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&h=600&fit=crop',
    slug: 'womens-clothing',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name_ar: 'الإلكترونيات',
    name_en: 'Electronics',
    description_ar: 'أحدث الأجهزة الإلكترونية من هواتف وسماعات وأجهزة ذكية',
    description_en: 'Latest electronic devices including phones, headphones, and smart gadgets',
    image_url: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&h=600&fit=crop',
    slug: 'electronics',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name_ar: 'الإكسسوارات',
    name_en: 'Accessories',
    description_ar: 'حقائب، ساعات، نظارات وإكسسوارات متنوعة',
    description_en: 'Bags, watches, sunglasses, and various accessories',
    image_url: 'https://images.unsplash.com/photo-1523779917675-b6ed3a42a561?w=800&h=600&fit=crop',
    slug: 'accessories',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockProducts = [
  {
    id: '1',
    name_ar: 'قميص كاجوال عصري',
    name_en: 'Modern Casual Shirt',
    description_ar: 'قميص قطني عالي الجودة بتصميم عصري مناسب للارتداء اليومي',
    description_en: 'High-quality cotton shirt with modern design suitable for daily wear',
    price_syp: 450000,
    price_usd: 108,
    stock: 50,
    category_id: '1',
    image_url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop',
    is_featured: true,
    slug: 'modern-casual-shirt',
    sizes: ['S', 'M', 'L', 'XL'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: mockCategories[0],
  },
  {
    id: '2',
    name_ar: 'سماعات لاسلكية',
    name_en: 'Wireless Headphones',
    description_ar: 'سماعات بلوتوث عالية الجودة مع إلغاء الضوضاء وبطارية تدوم 24 ساعة',
    description_en: 'High-quality Bluetooth headphones with noise cancellation and 24-hour battery',
    price_syp: 1200000,
    price_usd: 288,
    stock: 30,
    category_id: '3',
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
    is_featured: true,
    slug: 'wireless-headphones',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: mockCategories[2],
  },
  {
    id: '3',
    name_ar: 'ساعة ذكية',
    name_en: 'Smart Watch',
    description_ar: 'ساعة ذكية مع شاشة AMOLED وقياس معدل ضربات القلب وتتبع النشاط',
    description_en: 'Smart watch with AMOLED display, heart rate monitor, and activity tracking',
    price_syp: 2250000,
    price_usd: 540,
    stock: 25,
    category_id: '3',
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
    is_featured: true,
    slug: 'smart-watch',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: mockCategories[2],
  },
  {
    id: '4',
    name_ar: 'حقيبة جلدية فاخرة',
    name_en: 'Luxury Leather Bag',
    description_ar: 'حقيبة من الجلد الطبيعي الفاخر بتصميم أنيق وعملي',
    description_en: 'Premium genuine leather bag with elegant and practical design',
    price_syp: 900000,
    price_usd: 216,
    stock: 15,
    category_id: '4',
    image_url: 'https://images.unsplash.com/photo-1491637639811-60e2756cc1c7?w=400&h=400&fit=crop',
    is_featured: true,
    slug: 'luxury-leather-bag',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: mockCategories[3],
  },
  {
    id: '5',
    name_ar: 'فستان سهرة أنيق',
    name_en: 'Elegant Evening Dress',
    description_ar: 'فستان سهرة فاخر بتصميم راقي مناسب للمناسبات الخاصة',
    description_en: 'Luxurious evening dress with elegant design suitable for special occasions',
    price_syp: 1350000,
    price_usd: 324,
    stock: 20,
    category_id: '2',
    image_url: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400&h=400&fit=crop',
    is_featured: false,
    slug: 'elegant-evening-dress',
    sizes: ['S', 'M', 'L'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: mockCategories[1],
  },
  {
    id: '6',
    name_ar: 'بنطلون جينز رجالي',
    name_en: 'Men\'s Jeans',
    description_ar: 'بنطلون جينز مريح من القطن عالي الجودة بقصة عصرية',
    description_en: 'Comfortable high-quality cotton jeans with modern fit',
    price_syp: 525000,
    price_usd: 126,
    stock: 40,
    category_id: '1',
    image_url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop',
    is_featured: false,
    slug: 'mens-jeans',
    sizes: ['30', '32', '34', '36', '38'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: mockCategories[0],
  },
  {
    id: '7',
    name_ar: 'نظارة شمسية عصرية',
    name_en: 'Modern Sunglasses',
    description_ar: 'نظارة شمسية بحماية UV400 وإطار معدني أنيق',
    description_en: 'Sunglasses with UV400 protection and elegant metal frame',
    price_syp: 375000,
    price_usd: 90,
    stock: 60,
    category_id: '4',
    image_url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop',
    is_featured: false,
    slug: 'modern-sunglasses',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: mockCategories[3],
  },
  {
    id: '8',
    name_ar: 'هاتف ذكي',
    name_en: 'Smartphone',
    description_ar: 'هاتف ذكي بشاشة 6.5 بوصة وكاميرا عالية الدقة وبطارية 5000 مللي أمبير',
    description_en: '6.5-inch smartphone with high-resolution camera and 5000mAh battery',
    price_syp: 3750000,
    price_usd: 900,
    stock: 35,
    category_id: '3',
    image_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop',
    is_featured: true,
    slug: 'smartphone',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: mockCategories[2],
  },
];
