// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const supabase = createClient(
  "https://scbfcdslqctjhgeysxbw.supabase.co",
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjYmZjZHNscWN0amhnZXlzeGJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0MjgyODYsImV4cCI6MjA3ODAwNDI4Nn0.Vob9V3zVqg9JYDoMe_vhSoZgId_pz5EKY5pq0iI7UsE"
);
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(
//   SUPABASE_URL,
//   SUPABASE_PUBLISHABLE_KEY
// );

const products = [
  {
    id: 2,
    name: "سماعات لاسلكية",
    price: "799",
    originalPrice: "1299",
    rating: 4.8,
    reviews: 256,
    image:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    badge: "الأكثر مبيعاً",
  },
  {
    id: 3,
    name: "ساعة ذكية",
    price: "1499",
    originalPrice: "2199",
    rating: 4.6,
    reviews: 184,
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
    badge: "عرض خاص",
  },
  {
    id: 4,
    name: "حقيبة جلدية فاخرة",
    price: "599",
    originalPrice: "899",
    rating: 4.7,
    reviews: 94,
    image:
      "https://images.unsplash.com/photo-1491637639811-60e2756cc1c7?w=400&h=400&fit=crop",
    badge: "جديد",
  },
];
